name: evy
description: Evy is a Dart 2 Web Framework, with an ExpressJS like API.
version: 0.0.1
author: Carlos A. Escobar <ingcarlosandresescobar@gmail.com>
environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'